import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getAllPosts, PostMetadata, getAllTags } from "../src/post-api/api";
import Nav from "../src/components/Nav/Nav";
import Footer from "../src/components/Footer/Footer";
import Article from "../src/components/Article/Article";
import { useTheme } from "next-themes";
import { useState, useEffect, useContext, JSXElementConstructor, ReactElement, ReactFragment, ReactPortal } from "react";
import { MountedContext, useMountedContext } from "../src/MountedContext";

import { getRestaurantSlugs, getAllRestaurants, RestaurantData, getAllRestaurantData } from "../src/restaurant-api/api";

const things = [
    'one',
    'two',
    'three',
]

export default function Home({
  restaurants,
}: {
  restaurants: string[];
}) {
  const { systemTheme, theme, setTheme } = useTheme();
  const { mounted, setMounted } = useMountedContext();

  useEffect(() => {
    setMounted(true);
    // eslint-disable-next-line
  }, []);

  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav mounted={mounted} />

      <div
        className="dark:border-gray-700"
        style={{ width: "80%", marginLeft: "auto", marginRight: "auto" }}
      >
        <div className="pt-3 pb-3">
          <div className="border-l border-gray-300 dark:border-gray-700">
            <div className="ml-8 mt-8">
                {
                    restaurants.map((slug: string) => (
                        <div className="flex flex-col">
                            <Link href={`/restaurants/${slug}`}>
                            <a className={`text-xl font-semibold`}>{slug}</a>
                            </Link>
                        </div>
                    ))
                }
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </>
  );
}

export const getStaticProps = async () => {
  const restaurants = getRestaurantSlugs();
  console.log(restaurants)
  return {
    props: { restaurants },
  };
};
